# Generated by Django 3.2.7 on 2021-09-10 13:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('idComment', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, db_column='comment', max_length=350, null=True)),
                ('pontuation', models.IntegerField(db_column='pontuation')),
                ('username', models.CharField(blank=True, db_column='username', max_length=350, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItinearyRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'itineary_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItinearyRouteInterestPoints',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itinearyroute_id', models.IntegerField()),
                ('pointinterest_id', models.IntegerField()),
            ],
            options={
                'db_table': 'itineary_route_interest_points',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('idPagamento', models.AutoField(db_column='idPagamento', primary_key=True, serialize=False)),
                ('modo_pagamento', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PointInterest',
            fields=[
                ('idpercurso', models.AutoField(db_column='idPercurso', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('image', models.CharField(blank=True, max_length=322, null=True)),
            ],
            options={
                'db_table': 'Point_Interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=322, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'road_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoadVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'road_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('idViagem', models.AutoField(db_column='idViagem', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Travel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TravelSchedule',
            fields=[
                ('idAgendaViagem', models.AutoField(db_column='idAgendaViagem', primary_key=True, serialize=False)),
                ('dataAgenda', models.DateField()),
            ],
            options={
                'db_table': 'TravelSchedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('iduser', models.AutoField(db_column='idUser', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('max_cap', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
