# Generated by Django 3.2.7 on 2022-02-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointinterest',
            name='roadMap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roadMap', to='BestRideApi.roadmap'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='arquivado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='driver',
            field=models.ForeignKey(db_column='driver', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='BestRideApi.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='arquivado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itinearyrouteinterestpoints',
            name='id',
            field=models.BigAutoField(db_column='id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='city_id',
            field=models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.DO_NOTHING, to='BestRideApi.city'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(db_column='enterprise', on_delete=django.db.models.deletion.DO_NOTHING, to='BestRideApi.empresadriver'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.IntegerField(db_column='seats'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
