# Generated by Django 3.2.7 on 2021-10-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itinearyroute',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itinearyrouteinterestpoints',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pointinterest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roadmap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roadvehicle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='travelschedule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterModelTable(
            name='city',
            table='City',
        ),
    ]
