# Generated by Django 3.2.7 on 2021-10-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestRideApi', '0002_auto_20211025_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
    ]
